### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by Nemwel-Boniface** [usorfaitheloho/book-store#7]
## Hello @usorfaitheloho   :wave: :wave: 

You did a great job on your Bookstore project. I like the styling. I however have the following suggested changes to make your project even better:

![](https://media.giphy.com/media/xThta99fqDHWhicxVe/giphy.gif)
## :recycle: Suggested changes :recycle: 

- [ ] Great job fetching the data from the API successfully. However, the form accepts to submit even without the author of the book specified. You could use the following HTML form validations I recommend:

  1.  Using ```minlength``` and ```maxlength``` for validating the length of the author's as well as for the book title name. i put a very long text and it accepted it something I feel should be changed.
  2. Using a simple `required` attribute for the inputs will prevent someone from submitting an empty Book Title or Book Author section.

- [ ] In your buttons ie, add a book, remove button, I'd recommend giving them a CSS rule of `cursor: pointer` which makes it more intuitive when your users hover over them.

***Remember garbage in garbage out. This is where Form validation helps to put the data input in check***

You can leave me a comment in case you have any questions.

#Happycoding

**Comment by usorfaitheloho** [comment]
Thank you @Nemwel-Boniface , I will implement the suggestions.
